version: 2.1

jobs:
  build-x64:
    docker:
      - image: cimg/ruby:2.4-node
    steps:
      - checkout
      - run:
          name: Initialize vcpkg
          command: |
            bash data.sh
      - run:
          name: Build solution
          command: |
            echo "Done..."
  build-x86:
    docker:
      - image: cimg/ruby:2.5-node
    steps:
      - checkout
      - run:
          name: Initialize vcpkg
          command: |
            bash data.sh
      - run:
          name: Build solution
          command: |
            echo "Done..."
  build-arm:
    docker:
      - image: cimg/ruby:2.6-node
    steps:
      - checkout
      - run:
          name: Initialize vcpkg
          command: |
            bash data.sh
      - run:
          name: Build solution
          command: |
            echo "Done..."
  build-arm64:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - run:
          name: Initialize vcpkg
          command: |
            bash data.sh
      - run:
          name: Build solution
          command: |
            echo "Done..."

workflows:
  Build:
    jobs:
      - build-x64
      - build-x86
      - build-arm
      - build-arm64
